# 站点基础信息
baseURL = "/"
languageCode = "zh-cn"
title = "3hangq1ngの博客" #不为空logo才显示
theme = "PaperMod"
enableInlineShortcodes = true
enableEmoji = true
enableRobotsTXT = true
hasCJKLanguage = true
ShowBreadCrumbs = false
# 默认语言
defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir = false

# 构建选项
buildDrafts = false
buildFuture = false
buildExpired = false
# 网站左上角标签

[params.label]
# icon = ""
# iconSVG = """<svg t="1766125259221" class="icon" viewBox="0 0 5227 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="1609" width="200" height="200"><path d="M27.701895 283.324632h137.323789v62.895157a234.442105 234.442105 0 0 1 78.255158-57.829052 229.052632 229.052632 0 0 1 93.884632-19.132632c34.169263 0 65.050947 8.407579 92.591158 25.168842 27.486316 16.761263 49.637053 41.229474 66.45221 73.404632a221.669053 221.669053 0 0 1 80.249263-73.404632 219.082105 219.082105 0 0 1 103.909053-25.168842c38.965895 0 73.135158 9.054316 102.669474 27.162948 29.534316 18.108632 50.768842 41.768421 63.703579 70.925473s19.402105 76.638316 19.402105 142.282106v320.943157h-138.34779v-277.665684c0-61.978947-7.706947-104.016842-23.174737-125.952-15.36-21.989053-38.534737-32.929684-69.362526-32.929684-23.444211 0-44.517053 6.682947-63.110737 20.102737a119.107368 119.107368 0 0 0-41.498947 55.565474c-9.054316 23.659789-13.581474 61.601684-13.581474 113.933473v246.945684H378.772211v-265.054315c0-48.936421-3.610947-84.399158-10.832843-106.388211-7.221895-21.935158-18.054737-38.265263-32.552421-49.04421-14.443789-10.725053-31.905684-16.060632-52.385684-16.060632-22.905263 0-43.654737 6.736842-62.302316 20.318316-18.647579 13.581474-32.552421 32.660211-41.822315 57.128421-9.216 24.468211-13.850947 63.056842-13.850948 115.658105v243.442526H27.701895V283.324632M1740.638316 396.018526c-42.469053 0-77.716211 14.982737-105.795369 45.002106-28.025263 30.019368-42.091789 68.446316-42.091789 115.442526 0 47.265684 14.282105 86.177684 42.846316 116.682105 28.564211 30.504421 63.703579 45.756632 105.525894 45.756632 43.115789 0 78.848-14.982737 107.250527-45.002106 28.402526-30.019368 42.576842-69.362526 42.576842-117.975578 0-47.589053-14.174316-86.123789-42.576842-115.658106-28.402526-29.480421-64.350316-44.247579-107.789474-44.247579z m144.27621-323.907368h137.32379v758.460631h-137.32379v-57.882947c-26.785684 25.492211-53.625263 43.870316-80.626526 55.080421a225.818947 225.818947 0 0 1-87.632842 16.869053c-70.656 0-131.772632-27.432421-183.349895-82.243369-51.577263-54.810947-77.338947-122.933895-77.338947-204.422736 0-84.506947 24.953263-153.761684 74.805895-207.710316 49.906526-54.002526 110.538105-81.003789 181.894736-81.00379 32.821895 0 63.595789 6.197895 92.375579 18.647579 28.833684 12.395789 55.457684 30.989474 79.872 55.781053V72.111158zM2130.566737 283.324632h117.706105v68.985263c12.719158-27.216842 29.642105-47.858526 50.768842-61.925053 21.126737-14.066526 44.732632-17.785263 69.793684-17.785263 17.785263 0 43.762526 4.149895 67.69179 17.138526l-70.224842 104.717474a57.290105 57.290105 0 0 0-24.522105-4.958316c-21.072842 0-38.965895 13.042526-53.517474 39.181474-14.605474 26.192842-21.881263 77.500632-21.881263 153.923368l0.538947 26.677895v221.291789h-136.353684V283.324632M2855.019789 488.555789a137.754947 137.754947 0 0 0-53.625263-74.428631c-26.731789-19.132632-57.667368-28.672-92.968421-28.672-38.265263 0-71.895579 10.778947-100.783158 32.175158-18.108632 13.419789-34.869895 37.079579-50.337684 70.925473h297.714526z m137.32379 108.112843h-441.074526c6.359579 38.912 23.390316 69.847579 51.038315 92.806736 27.648 22.959158 62.949053 34.492632 105.903158 34.492632 51.253895 0 95.393684-17.946947 132.257685-53.894737l115.658105 54.37979c-28.833684 40.906105-63.380211 71.141053-103.585684 90.758736-40.259368 19.617684-88.010105 29.426526-143.36 29.426527-85.854316 0-155.755789-27.109053-209.704421-81.219369-54.002526-54.164211-81.003789-121.963789-81.00379-203.452631 0-83.482947 26.947368-152.791579 80.734316-207.97979 53.840842-55.134316 121.263158-82.728421 202.428631-82.728421 86.177684 0 156.240842 27.594105 210.189474 82.728421 54.002526 55.188211 81.003789 128.053895 81.00379 218.543158l-0.538948 26.138948zM3326.922105 396.018526c-42.415158 0-77.662316 14.982737-105.741473 45.002106-28.025263 30.019368-42.091789 68.446316-42.09179 115.442526 0 47.265684 14.282105 86.177684 42.846316 116.682105 28.564211 30.504421 63.757474 45.756632 105.525895 45.756632 43.115789 0 78.848-14.982737 107.250526-45.002106 28.402526-30.019368 42.576842-69.362526 42.576842-117.975578 0-47.589053-14.174316-86.123789-42.576842-115.658106-28.402526-29.480421-64.350316-44.247579-107.789474-44.247579z m144.384-112.64h137.269895V830.517895h-137.269895v-57.882948c-26.839579 25.492211-53.679158 43.870316-80.626526 55.080421-26.947368 11.210105-56.212211 16.869053-87.686737 16.869053-70.656 0-131.772632-27.432421-183.349895-82.243368-51.577263-54.810947-77.392842-122.933895-77.392842-204.422737 0-84.506947 25.007158-153.761684 74.913684-207.710316 49.852632-54.002526 110.484211-81.003789 181.786948-81.003789 32.875789 0 63.649684 6.197895 92.429474 18.647578 28.833684 12.395789 55.457684 30.989474 79.925894 55.781053v-60.362105zM3710.329263 283.324632h137.32379v62.895157c23.444211-25.869474 49.583158-45.109895 78.255158-57.829052a229.106526 229.106526 0 0 1 93.830736-19.132632 174.618947 174.618947 0 0 1 92.645053 25.168842c27.486316 16.761263 49.583158 41.229474 66.398316 73.404632a221.830737 221.830737 0 0 1 80.303158-73.404632 219.136 219.136 0 0 1 103.909052-25.168842c38.912 0 73.135158 9.054316 102.669474 27.162948 29.534316 18.108632 50.768842 41.768421 63.703579 70.925473s19.402105 76.638316 19.402105 142.282106v320.943157h-138.347789v-277.665684c0-61.978947-7.706947-104.016842-23.174737-125.952-15.36-21.989053-38.534737-32.929684-69.362526-32.929684-23.498105 0-44.517053 6.682947-63.110737 20.102737a118.999579 118.999579 0 0 0-41.498948 55.565474c-9.054316 23.659789-13.581474 61.601684-13.581473 113.933473v246.945684h-138.293895v-265.054315c0-48.936421-3.610947-84.399158-10.832842-106.388211-7.275789-21.935158-18.108632-38.265263-32.552421-49.04421-14.443789-10.725053-31.905684-16.060632-52.439579-16.060632-22.851368 0-43.600842 6.736842-62.248421 20.318316s-32.606316 32.660211-41.822316 57.128421c-9.216 24.468211-13.850947 63.056842-13.850947 115.658105v243.442526h-137.32379V283.324632M4846.753684 485.699368V280.576h136.730948v205.123368h204.530526v136.730948h-204.530526v204.530526h-136.784843V622.484211h-204.530526V485.699368h204.530526M1119.986526 512.916211l-95.016421-229.591579h-140.288l162.169263 394.778947 73.135158-165.187368M1323.924211 283.324632l-231.208422 506.394947-100.028631 216.117895h141.743158l330.213052-722.512842h-140.665263" fill="#111822" p-id="1610"></path></svg>"""
# iconHeight = 10

# 分页
[pagination]
pagerSize = 2
summaryLength = 140

# 压缩
[minify]
disableXML = true

# 自定义文章永久链接
[permalinks]
post = "/:title/"

[params.profileMode]
enabled = true
title = "blog" # optional default will be site title
subtitle = "This is subtitle"
imageUrl = "images/brent-cox-ydGRmobx5jA-unsplash.jpg" # optional
imageTitle = "pic" # optional
imageWidth = 120 # custom size
imageHeight = 120 # custom size

# 按钮列表（TOML 数组 of tables 写法）
[[params.profileMode.buttons]]
name = "About"
url = "/about"

[[params.profileMode.buttons]]
name = "Github"
url = "https://github.com/"

# [params.homeInfoParams]
# Title = "没有标准答案，只有随手写下的体验与心情。"
# Content = "不聊硬核参数，只记踩下电门时的风，屏幕亮起时的光，还有那些突然冒出来的、关于「体验」的细碎念头。"

# 文章页面封面图片
# 列表页和文章页封面显示策略
[params.cover]
responsiveImages = true
hidden = false
hiddenInList = false
hiddenInSingle = true

# 社交图标
[[params.socialIcons]]
name = "github"
url = "https://github.com/Luventious"

[[params.socialIcons]]
name = "email"
url = "mailto:1069263967@qq.com"

[[params.socialIcons]]
name = "rss"
url = "index.xml"

[[params.socialIcons]]
name = "link"
url = "https://umami.rzlnb.top/share/ymNY5tcAN7soVhBW/blog.rzlnb.top"

# 输出格式
[outputs]
home = ["HTML", "RSS", "JSON"]

# 允许原始 HTML
[markup.goldmark.renderer]
unsafe = true

# 分类
[taxonomies]
tag = "tags"
series = "series"

# 多语言配置
[languages.zh-cn]
languageName = "简中"
weight = 1
defaultContentLanguageInSubdir = false
