# 站点基础信息
baseURL = "/"
languageCode = "zh-cn"
title = ""
theme = "PaperMod"
enableInlineShortcodes = true
enableEmoji = true
enableRobotsTXT = true
hasCJKLanguage = true
# 默认语言
defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir = false

# 构建选项
buildDrafts = false
buildFuture = false
buildExpired = false
# 网站左上角标签

[params.label]
text = ""
icon = "images/logo.png"
iconSVG = ""
iconHeight = 35

# 分页
[pagination]
pagerSize = 15
summaryLength = 140

# 压缩
[minify]
disableXML = true

# 自定义文章永久链接
[permalinks]
post = "/:title/"

[params.homeInfoParams]
Title = "天府绿道APP / 设计提案"
Content = "@2020-2021 工作项目第一阶段汇报提案"

# 社交图标
[[params.socialIcons]]
name = "github"
url = "https://github.com/Luventious"

[[params.socialIcons]]
name = "email"
url = "mailto:1069263967@qq.com"

[[params.socialIcons]]
name = "rss"
url = "index.xml"

[[params.socialIcons]]
name = "link"
url = "https://umami.rzlnb.top/share/ymNY5tcAN7soVhBW/blog.rzlnb.top"

# 输出格式
[outputs]
home = ["HTML", "RSS", "JSON"]

# 允许原始 HTML
[markup.goldmark.renderer]
unsafe = true

# 分类
[taxonomies]
tag = "tags"
series = "series"

# 多语言配置
[languages.zh-cn]
languageName = "简中"
weight = 1
defaultContentLanguageInSubdir = false
