baseURL = "/"
languageCode = "zh-CN"
title = "3hangq1ng's blog"
theme = "PaperMod"

# å¯é€‰ï¼šé¦–é¡µå¸ƒå±€ã€åˆ†é¡µç­‰
[pagination]
pagerSize = 10

[params]
showSocial = true

disableKinds = ["RSS", "sitemap"]

[params.homeInfoParams]
Title = "Hi there ğŸ‘‹"
Content = "è¿™é‡Œå¯ä»¥å†™ç®€ä»‹ã€ä¿¡æ¯ã€é“¾æ¥æˆ–è€… About å†…å®¹"