baseURL = "/"
languageCode = "en-us"
title = "Shaunkyn"
theme = "PaperMod"

# 可选：首页布局、分页等
[pagination]
pagerSize = 10

disableKinds = ["RSS", "sitemap"]

[params]
  mainSections = ["posts"]
  dateFormat = "Jan 2, 2006"

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"
    disable = true

  [[module.imports]]
    path = "github.com/jpanther/congo/v2"
    disable = true