# 可以继续添加文章、关于我、标签等菜单
[[main]]
identifier = "home"
name = "Main"
url = "/"
weight = 1

[[main]]
identifier = "posts"
name = "Post"
url = "/posts/"
weight = 2

[[main]]
identifier = "about"
name = "about"
url = "/about/"
weight = 3
