# 全局参数
env = "production"
description = "有点儿意思~"
author = "3hangq1ng"
defaultTheme = "auto"

# 主题功能开关
ShowCodeCopyButtons = true
ShowReadingTime = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowWordCounts = true
ShowLastMod = true
ShowToc = true
TocOpen = true
comments = true
customHeadHTML = """
<link rel="preconnect" href="https://fonts.font.im">
<link rel="stylesheet" href="https://fonts.font.im/css?family=Hanalei+Fill">
"""


# Favicon 和 Apple Touch Icon
[params.assets]
favicon = "/images/avatar.jpg"

# 列表页和文章页封面显示策略
[params.cover]
hidden = false
hiddenInList = false
hiddenInSingle = true

# 搜索配置
[params.fuseOpts]
keys = ["title", "permalink", "summary"]

# 页脚年份
StartYear = 2024
EndYear = 2025
