baseURL = "/"
languageCode = 'zh-CN'
title = 'hugotoml-titile'
theme = 'hugo-noir'

defaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true
[languages]
  [languages.zh]
    languageName = "Chinese"
    title = "lang.titile"
    weight = 1
    contentDir = "content/CN"

# URL handling
relativeURLs = true
canonifyURLs = false

# Taxonomy configuration
[taxonomies]
  category = "categories"
  tag = "tags"


[params]
    name = "hugotoml"
    location = "Guangzhou-hugotoml-location"
    description = "hugotoml-description."
    profile_image = "/images/profile.jpg"
    discord = "johndoe123"
    github = "https://github.com/johndoe123"
    github_username = "Luventious"
    email = "1069263967@qq.com"
    twitter = "https://www.twitter.com/Luventious"
    twitter_username = "johndoe123"
    medium = "https://www.medium.com/@johndoe123"
    linkedin = "https://www.linkedin.com/in/dengshangqing"
    linkedin_username = "邓尚青"
    instagram = "https://instagram.com/johndoe123"
    leetcode = "https://leetcode.com/johndoe123"
    leetcode_username = "johndoe123"
    monkeytype = "https://monkeytype.com/profile/johndoe123"
    monkeytype_username = "johndoe123"
    kaggle = "https://www.kaggle.com/johndoe123"
    kaggle_username = "johndoe123"
    
[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    name = "Experience"
    url = "/experience/"
    weight = 2
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3
  [[menu.main]]
    name = "Blogs"
    url = "/blogs/"
    weight = 4
  [[menu.main]]
    name = "Contact Me"
    url = "/contact/"
    weight = 5